language: go

go: 
  - master

services:
  - docker

before_deploy:
  - wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
  - sudo unzip ninja-linux.zip -d /usr/local/bin/
  - sudo update-alternatives --install /usr/bin/ninja ninja /usr/local/bin/ninja 1 --force
  - ninja --version
  - bash ./scripts/build.sh
  - bash ./scripts/run-integration.sh



deploy:
  provider: releases
  api_key:
    secure: "pCQIijD1MRL5cmRV52fh/H0qB97++3f2J47VqYxkIV3FC3J9CTWDwLKPC2ho+GxbvkQjpbYzSCl+6nTqQddynoNNxIWqXEGVJ2kIxZpykvGfqdws6aH4lJ+tR1o3KosIe9XJjHw1dXvGqU9dhme7/R4TVobp7syOy4263+tjAp7W9JPhNrBG/PX9YB6X7mbdd6aQQGVTbQeK6FprVF1Tz0ngxa1JcEurp0tuHrwKBLA625xZKsSfszXb+2tsSuDrGCQbewSo6wxhyWhKqLuyKJcJcDQlDF4wF/i43goOghpCmmMkH01dHAW+eEYCHAuM7PWrG3gSgfb78hrha1wmQBdJ98gTX8pdBd5cWkPttDg0rmR+joAfdKcnHtDXG/y7OCotBkDFqtE8L2xaVGDTZyCYJiMbnL9fyIvKcpicv6TkPXY+JYlVujUoa3iO145+NcE9ID5SYYUYOvq6tr5URKtVul0HRbcdaHqhdS4Kk5UgZoZr9RU0CTR0WSqtGKCmJEKHgPYnIzw3FsKKkg/5k8Bs8shx5PBt/pre8A7HMRZQK1LkjGH2PPStCnovBF6WyhbW0RmARP0qZbfkoaQ5LV194a0tdNirKNex2QBZTRSipsN44e2NTXbYGMcr9AK+bCO55+geicTSZMv3Sv1k7uyUFFmdqIIa5YSZWmlwFec="
  file: "./out/bin/bood"
  skip_cleanup: true